# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 02:49
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='\\d{16}')], verbose_name='Número do cartão')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('expiration_date', models.DateField(verbose_name='Data de validade')),
                ('verification_code', models.SmallIntegerField(verbose_name='Código de segurança')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
