# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 06:20
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='\\d{16}')], verbose_name='Número do cartão')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('expiration_date', models.DateField(verbose_name='Data de validade')),
                ('verification_code', models.SmallIntegerField(verbose_name='Código de segurança')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Group')),
            ],
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expiration_date_month',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Mês de Vencimento'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expiration_date_year',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Ano de Vencimento'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='cards',
            field=models.ManyToManyField(to='account.CreditCard'),
        ),
    ]
