# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160828_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='cards',
            field=models.ManyToManyField(blank=True, to='account.CreditCard'),
        ),
    ]
